### ISSUE TITLE
Remove Ubuntu-16.04 on CI

### ISSUE THREAD

**Issue by k-matsuzawa** [cryptogarageinc/cfd-core#292]
# Overview

- Remove Ubuntu-16.04 on CI

# Completion condition

- Remove Ubuntu-16.04 on CI matrix.

**Comment by k-matsuzawa** [comment]
target:
- cfd-core
- cfd
- cloudhsm (util)
  - create release binary. Research the OS you are currently using.

**Comment by k-matsuzawa** [comment]
- cfd-core done.
- cfd done

**Comment by k-matsuzawa** [comment]
Remove Ubuntu 16.04: 2021/09/20

**Comment by ko-matsu** [comment]
実施済み。クローズすること。
