### ISSUE TITLE
Support BIP-0086

### ISSUE THREAD

**Issue by ko-matsu** [cryptogarageinc/cfd-core#307]
# Overview

- BIP-0086をサポートする
  - 現状はTaprootScriptTreeに機能を置いているが、TapLeafじゃないと動かないようにガードしている。
  - そのため、ただの32byte値(xonly pubkey)でもTapTweak処理が動作するように変更する必要がある。
  - C-APIについては既存のAPIで対応できるか要調査。JS/wasmは引数での処理判断が妥当かチェック。

# Completion condition

- BIP-0086で想定する処理が行えること。

**Comment by k-matsuzawa** [comment]
cfd-core: TapBranchでの動作はOK。ただしdescriptorに問題があるため修正に時間がかかる見込み。
